version: "3"

services:
    redis:
        image: "redis:alpine"
        
        ports:
            - 6379:6379
            
        networks:
            - microservices

networks:
    microservices:
      driver: bridge